
#define FRAME_RATE 60

#define GRAVITATE_BODIES true

#define BODY_COUNT 10
#define GRAVITY 0.001
#define MAX_BODY_SIZE 400
#define MIN_BODY_SIZE 50

#define FUEL_MASS 2.0
#define FUEL_START 10000
#define SHIP_MASS 2000
#define BOUNCE_FACTOR 0.1
#define THRUST_X 250
#define THRUST_Y 1000
#define EARTH_HEIGHT 50
#define HORIZONTAL_FUEL_CONSUMPTION 2.0
#define VERTICAL_FUEL_CONSUMPTION 5.0
#define BIASES_FILE "data/cognative_biases.csv"
