
#define WINDOW_WIDTH 1*1280
#define WINDOW_HEIGHT 1.25*768
#define FRAME_RATE 1.0/60.0

#define GRAVITATE_BODIES false

#if GRAVITATE_BODIES
#define BODY_COUNT 5
#define GRAVITY 0 //0.01
#define MAX_BODY_SIZE 200
#define MIN_BODY_SIZE 20
#else
#define BODY_COUNT 10
#define GRAVITY 0.01
#define MAX_BODY_SIZE 400
#define MIN_BODY_SIZE 50
#endif

#define FUEL_MASS 2.0
#define FUEL_START 10000
#define SHIP_MASS 2000
#define THRUST_X 250
#define THRUST_Y 1000
#define EARTH_HEIGHT 50
#define HORIZONTAL_FUEL_CONSUMPTION 2.0
#define VERTICAL_FUEL_CONSUMPTION 5.0
#define BIASES_FILE "data/cognative_biases.csv"